version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    command: ["postgres", "-c", "tcp_listen_addresses='*'"]
  
  bot:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      STORAGE_API_TOKEN: ${STORAGE_API_TOKEN}
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    depends_on:
      - db

volumes:
  postgres_data: